[package]
name = "tyedev"
version = "0.1.0"
edition = "2021"
description = "Create and manage devcontainer configuration"
repository = "https://github.com/CodeMan99/tyedev"
license = "ISC"
readme = "README.md"
authors = ["Cody Taylor <codemister99@yahoo.com>"]
keywords = ["devcontainers", "containers", "vscode", "development", "configuration", "cli"]
categories = ["config", "command-line-utilities", "development-tools", "virtualization"]
include = ["LICENSE.txt", "src/", "static/"]

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/{ name }-{ version }-{ target }{ archive-suffix }"
bin-dir = "{ name }-{ version }-{ target }/{ bin }{ binary-ext }"
pkg-fmt = "tgz"

[dependencies]
ascii_table = { version = "4.0.3", features = ["auto_table_width"] }
clap = { version = "4.4.6", features = ["derive", "wrap_help"] }
clap-verbosity-flag = "2.1.0"
clap_complete = { version = "4.4.4", optional = true }
dirs = "5.0.1"
env_logger = "0.10.1"
human_format = "1.0.3"
inquire = { version = "0.6.2", features = ["editor"] }
log = "0.4.20"
oci-spec = "0.5.8" # using specifically this version to match ocipkg.
ocipkg = "0.2.8"
regex = "1.10.2"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = { version = "1.0.107", features = ["preserve_order"] }
serde_jsonc = { version = "1.0.107", features = ["preserve_order"] }
tar = "0.4.40"

[features]
default = ["completions"]
completions = ["dep:clap_complete"]
