[package]
name = "devconf"
version = "0.1.0"
edition = "2021"

[dependencies]
ascii_table = { version = "4.0.3", features = ["auto_table_width"] }
clap = { version = "4.4.6", features = ["derive", "wrap_help"] }
dirs = "5.0.1"
human_format = "1.0.3"
inquire = { version = "0.6.2", features = ["editor"] }
oci-spec = "0.6.4"
ocipkg = { git = "https://github.com/CodeMan99/ocipkg", branch = "feat/get-image-layer", version = "0.2.8" }
regex = "1.10.2"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = { version = "1.0.107", features = ["preserve_order"] }
serde_jsonc = { version = "1.0.107", features = ["preserve_order"] }
tar = "0.4.40"

[dev-dependencies]
tempfile = "3.8.1"
